# Clear plots
if(!is.null(dev.list())) dev.off()
# Clear console
cat("\014") 
# Clean workspace
rm(list=ls())
#Install and load the packages
#install.packages(c("ggplot2", "ggpubr", "tidyverse", "broom", "AICcmodavg"))
#Loading these packages into your R environment 
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(broom)
library(AICcmodavg)
#Setting the working directory
setwd("D:/2020DESKTOP/Uni/Applied Statistics/Project")
#Load the data into R
crop.data <- read.csv("Plant_tissue_1990_2014.csv", header = TRUE, colClasses = c("factor", "factor", "factor", "factor", "factor", "factor", "factor", "factor", "factor", "factor", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
#Cheking that the data has read in correctly
summary(crop.data)
cat("\014") 
#Checking that the data meets the assumptions
plot(crop.data$Leaf_N_per, crop.data$Year,main="The Sine Function",xlab="sin(x)",ylab="sin(x)")
#Normality, Independence of observations, Homogeneity of variance among groups
par(mfrow=c(3,5))
hist(crop.data$Leaf_N_per)                    
hist(crop.data$Leaf_P_per)
hist(crop.data$Leaf_K_per)
hist(crop.data$Leaf_Ca_per)
hist(crop.data$Leaf_Mg_per)
hist(crop.data$Leaf_S_per)
hist(crop.data$Leaf_B_ppm)
hist(crop.data$Leaf_Fe_ppm)
hist(crop.data$Leaf_Cu_ppm)
hist(crop.data$Leaf_Zn_ppm)
hist(crop.data$Leaf_Al_ppm)
hist(crop.data$Leaf_Mn_ppm)
hist(crop.data$Leaf_Na_ppm)
if(!is.null(dev.list())) dev.off()
#One-way ANOVA ----------------------------------------------------                   
one.way1 <- aov(Leaf_N_per ~ Fert_st, data = crop.data)
summary(one.way1)
cat("\014") 
one.way2 <- aov(Leaf_P_per ~ Fert_st, data = crop.data)
summary(one.way2) 
cat("\014") 
one.way3 <- aov(Leaf_K_per ~ Fert_st, data = crop.data)
summary(one.way3)
cat("\014") 
one.way4 <- aov(Leaf_Ca_per ~ Fert_st, data = crop.data)
summary(one.way4)
cat("\014") 
one.way5 <- aov(Leaf_Mg_per ~ Fert_st, data = crop.data)
summary(one.way5)
cat("\014") 
one.way6 <- aov(Leaf_S_per ~ Fert_st, data = crop.data)
summary(one.way6)
cat("\014") 
one.way7 <- aov(Leaf_B_ppm ~ Fert_st, data = crop.data)
summary(one.way7)
cat("\014") 
one.way8 <- aov(Leaf_Fe_ppm ~ Fert_st, data = crop.data)
summary(one.way8)
cat("\014") 
one.way9 <- aov(Leaf_Cu_ppm ~ Fert_st, data = crop.data)
summary(one.way9)
cat("\014") 
one.way10 <- aov(Leaf_Zn_ppm ~ Fert_st, data = crop.data)
summary(one.way10)
cat("\014") 
one.way11 <- aov(Leaf_Al_ppm ~ Fert_st, data = crop.data)
summary(one.way11)
cat("\014") 
one.way12 <- aov(Leaf_Mn_ppm ~ Fert_st, data = crop.data)
summary(one.way12)
cat("\014") 
one.way13 <- aov(Leaf_Na_ppm ~ Fert_st, data = crop.data)
summary(one.way13)
cat("\014") 
#Two-way ANOVA ----------------------------------------------------
two.way1 <- aov(Leaf_N_per ~ Fert_st + Treatment_st , data = crop.data)
summary(two.way1)
cat("\014") 
two.way2 <- aov(Leaf_P_per ~ Fert_st + Treatment_st, data = crop.data)
summary(two.way2) 
cat("\014") 
two.way3 <- aov(Leaf_K_per ~ Fert_st + Treatment_st, data = crop.data)
summary(two.way3)
cat("\014") 
two.way4 <- aov(Leaf_Ca_per ~ Fert_st + Treatment_st, data = crop.data)
summary(two.way4)
cat("\014") 
two.way5 <- aov(Leaf_Mg_per ~ Fert_st + Treatment_st, data = crop.data)
summary(two.way5)
cat("\014") 
two.way6 <- aov(Leaf_S_per ~ Fert_st + Treatment_st, data = crop.data)
summary(two.way6)
cat("\014") 
two.way7 <- aov(Leaf_B_ppm ~ Fert_st + Treatment_st, data = crop.data)
summary(two.way7)
cat("\014") 
two.way8 <- aov(Leaf_Fe_ppm ~ Fert_st + Treatment_st, data = crop.data)
summary(two.way8)
cat("\014") 
two.way9 <- aov(Leaf_Cu_ppm ~ Fert_st + Treatment_st, data = crop.data)
summary(two.way9)
cat("\014") 
two.way10 <- aov(Leaf_Zn_ppm ~ Fert_st + Treatment_st, data = crop.data)
summary(two.way10)
cat("\014") 
two.way11 <- aov(Leaf_Al_ppm ~ Fert_st + Treatment_st, data = crop.data)
summary(two.way11)
cat("\014") 
two.way12 <- aov(Leaf_Mn_ppm ~ Fert_st + Treatment_st, data = crop.data)
summary(two.way12)
cat("\014") 
two.way13 <- aov(Leaf_Na_ppm ~ Fert_st + Treatment_st, data = crop.data)
summary(two.way13)
cat("\014") 
#Adding interactions between variables ----------------------------------
interaction1 <- aov(Leaf_N_per ~ Fert_st * Treatment_st * Tillage_st * Rep , data = crop.data)
summary(interaction1)
cat("\014") 
interaction2 <- aov(Leaf_P_per ~ Fert_st * Treatment_st * Tillage_st * Rep, data = crop.data)
summary(interaction2) 
cat("\014") 
interaction3 <- aov(Leaf_K_per ~ Fert_st * Treatment_st * Tillage_st * Rep, data = crop.data)
summary(interaction3)
cat("\014") 
interaction4 <- aov(Leaf_Ca_per ~ Fert_st * Treatment_st * Tillage_st * Rep, data = crop.data)
summary(interaction4)
cat("\014") 
interaction5 <- aov(Leaf_Mg_per ~ Fert_st * Treatment_st * Tillage_st * Rep, data = crop.data)
summary(interaction5)
cat("\014") 
interaction6 <- aov(Leaf_S_per ~ Fert_st * Treatment_st * Tillage_st * Rep, data = crop.data)
summary(interaction6)
cat("\014") 
interaction7 <- aov(Leaf_B_ppm ~ Fert_st * Treatment_st * Tillage_st * Rep, data = crop.data)
summary(interaction7)
cat("\014") 
interaction8 <- aov(Leaf_Fe_ppm ~ Fert_st * Treatment_st * Tillage_st * Rep, data = crop.data)
summary(interaction8)
cat("\014") 
interaction9 <- aov(Leaf_Cu_ppm ~ Fert_st * Treatment_st * Tillage_st * Rep, data = crop.data)
summary(interaction9)
cat("\014") 
interaction10 <- aov(Leaf_Zn_ppm ~ Fert_st * Treatment_st * Tillage_st * Rep, data = crop.data)
summary(interaction10)
cat("\014") 
interaction11 <- aov(Leaf_Al_ppm ~ Fert_st * Treatment_st * Tillage_st * Rep, data = crop.data)
summary(interaction11)
cat("\014") 
interaction12 <- aov(Leaf_Mn_ppm ~ Fert_st * Treatment_st * Tillage_st * Rep, data = crop.data)
summary(interaction12)
cat("\014") 
interaction13 <- aov(Leaf_Na_ppm ~ Fert_st * Treatment_st * Tillage_st * Rep, data = crop.data)
summary(interaction13)
cat("\014") 
#Adding a blocking variable --------------------------------------------------
blocking1 <- aov(Leaf_N_per ~ Fert_st + Treatment_st + Tillage_st + Rep, data = crop.data)
summary(blocking1)
cat("\014") 
blocking2 <- aov(Leaf_P_per ~ Fert_st + Treatment_st + Tillage_st + Rep, data = crop.data)
summary(blocking2) 
cat("\014") 
blocking3 <- aov(Leaf_K_per ~ Fert_st + Treatment_st + Tillage_st + Rep, data = crop.data)
summary(blocking3)
cat("\014") 
blocking4 <- aov(Leaf_Ca_per ~ Fert_st + Treatment_st + Tillage_st + Rep, data = crop.data)
summary(blocking4)
cat("\014") 
blocking5 <- aov(Leaf_Mg_per ~ Fert_st + Treatment_st + Tillage_st + Rep, data = crop.data)
summary(blocking5)
cat("\014") 
blocking6 <- aov(Leaf_S_per ~ Fert_st + Treatment_st + Tillage_st + Rep, data = crop.data)
summary(blocking6)
cat("\014") 
blocking7 <- aov(Leaf_B_ppm ~ Fert_st + Treatment_st + Tillage_st + Rep, data = crop.data)
summary(blocking7)
cat("\014") 
blocking8 <- aov(Leaf_Fe_ppm ~ Fert_st + Treatment_st + Tillage_st + Rep, data = crop.data)
summary(blocking8)
cat("\014") 
blocking9 <- aov(Leaf_Cu_ppm ~ Fert_st + Treatment_st + Tillage_st + Rep, data = crop.data)
summary(blocking9)
cat("\014") 
blocking10 <- aov(Leaf_Zn_ppm ~ Fert_st + Treatment_st + Tillage_st + Rep, data = crop.data)
summary(blocking10)
cat("\014") 
blocking11 <- aov(Leaf_Al_ppm ~ Fert_st + Treatment_st + Tillage_st + Rep, data = crop.data)
summary(blocking11)
cat("\014") 
blocking12 <- aov(Leaf_Mn_ppm ~ Fert_st + Treatment_st + Tillage_st + Rep, data = crop.data)
summary(blocking12)
cat("\014") 
blocking13 <- aov(Leaf_Na_ppm ~ Fert_st + Treatment_st + Tillage_st + Rep, data = crop.data)
summary(blocking13)
cat("\014") 
#Find the best-fit model -------------------------------------------------------------------
library(AICcmodavg)
model.set <- list(one.way1, two.way1, interaction1, blocking1)
model.names <- c("one.way", "two.way", "interaction", "blocking")
aictab(model.set, modnames = model.names)
model.set <- list(one.way2, two.way2, interaction2, blocking2)
model.names <- c("one.way", "two.way", "interaction", "blocking")
aictab(model.set, modnames = model.names)
model.set <- list(one.way3, two.way3, interaction3, blocking3)
model.names <- c("one.way", "two.way", "interaction", "blocking")
aictab(model.set, modnames = model.names)
model.set <- list(one.way4, two.way4, interaction4, blocking4)
model.names <- c("one.way", "two.way", "interaction", "blocking")
aictab(model.set, modnames = model.names)
model.set <- list(one.way5, two.way5, interaction5, blocking5)
model.names <- c("one.way", "two.way", "interaction", "blocking")
aictab(model.set, modnames = model.names)
model.set <- list(one.way6, two.way6, interaction6, blocking6)
model.names <- c("one.way", "two.way", "interaction", "blocking")
aictab(model.set, modnames = model.names)
model.set <- list(one.way7, two.way7, interaction7, blocking7)
model.names <- c("one.way", "two.way", "interaction", "blocking")
aictab(model.set, modnames = model.names)
model.set <- list(one.way8, two.way8, interaction8, blocking8)
model.names <- c("one.way", "two.way", "interaction", "blocking")
aictab(model.set, modnames = model.names)
model.set <- list(one.way9, two.way9, interaction9, blocking9)
model.names <- c("one.way", "two.way", "interaction", "blocking")
aictab(model.set, modnames = model.names)
model.set <- list(one.way10, two.way10, interaction10, blocking10)
model.names <- c("one.way", "two.way", "interaction", "blocking")
aictab(model.set, modnames = model.names)
model.set <- list(one.way11, two.way11, interaction11, blocking11)
model.names <- c("one.way", "two.way", "interaction", "blocking")
aictab(model.set, modnames = model.names)
model.set <- list(one.way12, two.way12, interaction12, blocking12)
model.names <- c("one.way", "two.way", "interaction", "blocking")
aictab(model.set, modnames = model.names)
model.set <- list(one.way13, two.way13, interaction13, blocking13)
model.names <- c("one.way", "two.way", "interaction", "blocking")
aictab(model.set, modnames = model.names)
#Check for homoscedasticity ----------------------------------------------------------------
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(one.way1)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(one.way2)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(one.way3)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(one.way4)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(one.way5)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(one.way6)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(one.way7)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(one.way8)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(one.way9)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(one.way10)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(one.way11)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(one.way12)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(one.way13)
par(mfrow=c(1,1))
#--------------------------------------------------------------------
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(two.way1)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(two.way2)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(two.way3)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(two.way4)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(two.way5)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(two.way6)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(two.way7)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(two.way8)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(two.way9)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(two.way10)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(two.way11)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(two.way12)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(two.way13)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
#-----------------------------------------------------------------------
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(interaction1)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(interaction2)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(interaction3)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(interaction4)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(interaction5)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(interaction6)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(interaction7)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(interaction8)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(interaction9)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(interaction10)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(interaction11)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(interaction12)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
#par(mfrow=c(2,2))
#plot(interaction13)
#par(mfrow=c(1,1))
#if(!is.null(dev.list())) dev.off()
#-----------------------------------------------------------------------
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(interaction1)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(blocking2)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(blocking3)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(blocking4)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(blocking5)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(blocking6)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(blocking7)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(blocking8)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(blocking9)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(blocking10)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(blocking11)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(blocking12)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
par(mfrow=c(2,2))
plot(blocking13)
par(mfrow=c(1,1))
if(!is.null(dev.list())) dev.off()
#Do a post-hoc test-Pairwise ----------------------------------------------------------------
tukey.one.way1<-TukeyHSD(one.way1)
tukey.one.way1
cat("\014") 
tukey.two.way1<-TukeyHSD(two.way1)
tukey.two.way1
cat("\014") 
tukey.interaction1<-TukeyHSD(interaction1)
tukey.interaction1
cat("\014")
tukey.blocking1<-TukeyHSD(blocking1)
tukey.blocking1
cat("\014") 
tukey.one.way2<-TukeyHSD(one.way2)
tukey.one.way2
cat("\014") 
tukey.two.way2<-TukeyHSD(two.way2)
tukey.two.way2
cat("\014") 
tukey.interaction2<-TukeyHSD(interaction2)
tukey.interaction2
cat("\014")
tukey.blocking2<-TukeyHSD(blocking2)
tukey.blocking2
cat("\014") 
tukey.one.way3<-TukeyHSD(one.way3)
tukey.one.way3
cat("\014") 
tukey.two.way3<-TukeyHSD(two.way3)
tukey.two.way3
cat("\014") 
tukey.interaction3<-TukeyHSD(interaction3)
tukey.interaction3
cat("\014")
tukey.blocking3<-TukeyHSD(blocking3)
tukey.blocking3
cat("\014") 
tukey.one.way4<-TukeyHSD(one.way4)
tukey.one.way4
cat("\014") 
tukey.two.way4<-TukeyHSD(two.way4)
tukey.two.way4
cat("\014") 
tukey.interaction4<-TukeyHSD(interaction4)
tukey.interaction4
cat("\014")
tukey.blocking4<-TukeyHSD(blocking4)
tukey.blocking4
cat("\014") 
tukey.one.way5<-TukeyHSD(one.way5)
tukey.one.way5
cat("\014") 
tukey.two.way5<-TukeyHSD(two.way5)
tukey.two.way5
cat("\014") 
tukey.interaction5<-TukeyHSD(interaction5)
tukey.interaction5
cat("\014")
tukey.blocking5<-TukeyHSD(blocking5)
tukey.blocking5
cat("\014") 
tukey.one.way6<-TukeyHSD(one.way6)
tukey.one.way6
cat("\014") 
tukey.two.way6<-TukeyHSD(two.way6)
tukey.two.way6
cat("\014") 
tukey.interaction6<-TukeyHSD(interaction6)
tukey.interaction6
cat("\014")
tukey.blocking<-TukeyHSD(blocking6)
tukey.blocking6
cat("\014") 
tukey.one.way7<-TukeyHSD(one.way7)
tukey.one.way7
cat("\014") 
tukey.two.way7<-TukeyHSD(two.way7)
tukey.two.way7
cat("\014") 
tukey.interaction7<-TukeyHSD(interaction7)
tukey.interaction7
cat("\014")
tukey.blocking7<-TukeyHSD(blocking7)
tukey.blocking7
cat("\014") 
tukey.one.way8<-TukeyHSD(one.way8)
tukey.one.way8
cat("\014") 
tukey.two.way8<-TukeyHSD(two.way8)
tukey.two.way8
cat("\014") 
tukey.interaction8<-TukeyHSD(interaction8)
tukey.interaction8
cat("\014")
tukey.blocking8<-TukeyHSD(blocking8)
tukey.blocking8
cat("\014") 
tukey.one.way9<-TukeyHSD(one.way9)
tukey.one.way9
cat("\014") 
tukey.two.way9<-TukeyHSD(two.way9)
tukey.two.way9
cat("\014") 
tukey.interaction9<-TukeyHSD(interaction9)
tukey.interaction9
cat("\014")
tukey.blocking9<-TukeyHSD(blocking9)
tukey.blocking9
cat("\014") 
tukey.one.way10<-TukeyHSD(one.way10)
tukey.one.way10
cat("\014") 
tukey.two.way10<-TukeyHSD(two.way10)
tukey.two.way10
cat("\014") 
tukey.interaction10<-TukeyHSD(interaction10)
tukey.interaction10
cat("\014")
tukey.blocking10<-TukeyHSD(blocking10)
tukey.blocking10
cat("\014") 
tukey.one.way11<-TukeyHSD(one.way11)
tukey.one.way11
cat("\014") 
tukey.two.way11<-TukeyHSD(two.way11)
tukey.two.way11
cat("\014") 
tukey.interaction11<-TukeyHSD(interaction11)
tukey.interaction11
cat("\014")
tukey.blocking11<-TukeyHSD(blocking11)
tukey.blocking11
cat("\014") 
tukey.one.way12<-TukeyHSD(one.way12)
tukey.one.way12
cat("\014") 
tukey.two.way12<-TukeyHSD(two.way12)
tukey.two.way12
cat("\014") 
tukey.interaction12<-TukeyHSD(interaction12)
tukey.interaction12
cat("\014")
tukey.blocking12<-TukeyHSD(blocking12)
tukey.blocking12
cat("\014") 
tukey.one.way13<-TukeyHSD(one.way13)
tukey.one.way13
cat("\014") 
tukey.two.way13<-TukeyHSD(two.way13)
tukey.two.way13
cat("\014") 
tukey.interaction13<-TukeyHSD(interaction13)
tukey.interaction13
cat("\014")
tukey.blocking13<-TukeyHSD(blocking13)
tukey.blocking13
cat("\014") 
#Plot the results in a graph
two.way.plot <- ggplot(crop.data, aes(x = Treatment_st, y = Leaf_N_per, group=Fert_st)) +
  geom_point(cex = 1.5, pch = 1.0,position = position_jitter(w = 0.1, h = 0))
two.way.plot  
two.way.plot <- two.way.plot +
  stat_summary(fun.data = 'mean_se', geom = 'errorbar', width = 0.2) +
  stat_summary(fun.data = 'mean_se', geom = 'pointrange') +
  geom_point(data=mean.Leaf_N_per.data, aes(x=Treatment_st, y=Leaf_N_per))

two.way.plot
two.way.plot <- two.way.plot +
  theme_classic2() +
  labs(title = "Cron Leaf_N_per in response to fertilizer mix and Treatment",
       x = "Treatment",
       y = "Leaf_N_per")

two.way.plot
if(!is.null(dev.list())) dev.off()